title: the journal of francis billones 
email: francisd.billones@gmail.com
description: pseudo-intellectual rants about tech and society 
baseurl: ""
url: "https://journal.francisdb.net"
twitter_username: francishubertdb 
github_username: francisdbillones 

# Build settings
# theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]

google_analytics_id: "G-W21423KMLR"

# assets:
#   source_maps: true
#   destination: "/public"
#   compression: true
#   gzip: true
#   defaults:
#     integrity:
#       {css,img,js}: false
  
#   caching:
#     enabled: true
#     path: ".jekyll-cache/assets"
#     type: file
  
#   precompile: []
#   raw_precompile: [
#     #
#   ]

#   sources:
#     - public/css

# sass:
#   style: compressed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
